### ISSUE TITLE
Supporting Documentation: Should add a code review document to adhere to reproducible code guidelines.

### ISSUE THREAD

**Issue by RadhikaKaul** [worldbank/DIMEwiki#13]
Maybe attach this link for people to refer to it before submitting their publication package [https://www.poverty-action.org/sites/default/files/publications/IPA's%20Best%20Practices%20for%20Data%20and%20Code%20Management_Nov2015.pdf](url)

**Comment by roshni13khincha** [comment]
Discussed and not required.
