### ISSUE TITLE
Moving de-identification section before data cleaning section

### ISSUE THREAD

**Issue by RadhikaKaul** [worldbank/DIMEwiki#9]
We would want the incoming interns/RAs who will start cleaning the data for publication to first drop all PII information before spending time in labeling all the variables which ultimately were going to be dropped anyway.

**Comment by kbjarkefur** [comment]
Can you link to the file in this repository you are making this comment to? Or is this a new checklist? 
Otherwise it is difficult for anyone else to follow what you are referring to.

**Comment by RadhikaKaul** [comment]
I added 'microdata checklist' as a label. Let me know if that's okay or if I should put it in the issue title as well to make it clearer.

**Comment by roshni13khincha** [comment]
Makes sense. @RadhikaKaul has incorporated in the new checklist.
